### ISSUE TITLE
Optimize code

### ISSUE THREAD

**Issue by Rohit-554** [Rohit-554/Hackerrank_solution#2]
Hey, 
Please Optimize the "Repeatedstrings.py" to the best time complexity 
comment if you do not understood something

**Comment by aserputov** [comment]
@Rohit-554 I would like to work on this issue. Could you please assign me ?

**Comment by aserputov** [comment]
@Rohit-554 Honestly saying I looked through the project and I can't understand what is it and how to use it, can you please provide more Information, because README is kind da empty .

**Comment by Rohit-554** [comment]
Ya sure , Just fork the Repeatedstrings.py in the main branch it's hackerrnak solution for the question https://www.hackerrank.com/challenges/repeated-string/problem   You just need to make a optimized solution for this and give your PR

**Comment by aserputov** [comment]
Yea, I'm in love with this issue !! I will do it now :)

**Comment by aserputov** [comment]
https://github.com/Rohit-554/Hackerrank_solution/blob/19a80ddc89fa6888e1a9d78496f9486961b51a67/Repeatedstrings.py#L7
I actually found a bug in your code. It will always give the size of the string. I will fix it.

**Comment by aserputov** [comment]
Could you please close the issue too?
@Rohit-554

**Comment by Rohit-554** [comment]
@aserputov thankyou for your contribution you can make a new pr of hackerrank solutions i will be happy to add them
